FROM traefik:raclette-alpine
MAINTAINER Jonathan Meier <jonathan.w.meier@gmail.com>

RUN groupadd -g 10001 traefik && \
    useradd -r -u 10001 -g traefik traefik && \
    chown -R traefik:traefik / && \
    setcap 'cap_net_bind_service=+ep' /bin/traefik

USER traefik

ENTRYPOINT ["/traefik"]
