version: '2'

services:
  traefik:
    image: traefik:1.5.4
    restart: always
    command: traefik --acme.domains='${WEBDAV_DOMAIN}' --docker.domain='${WEBDAV_DOMAIN}'
    ports:
      - 80:80
      - 443:443
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${TRAEFIK_CONFIG_DIR}/traefik.toml:/traefik.toml
      - ${TRAEFIK_CONFIG_DIR}/acme.json:/acme.json
    container_name: traefik

networks:
  web:
    external: true
