version: "3"

services:
  app:
    image: python:3.6-stretch
    networks:
      - web
    ports:
      - 8000:8000
    command: ["python", "-m", "http.server", "8000"]
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:${DOMAIN}"
      - "traefik.basic.port=8000"
      - "traefik.basic.protocol=http"

networks:
  web:
    external: true
