version: '3.4'
services:
  webdav-nginx:
    build:
      context: ..
      dockerfile: Dockerfile.nginx
    environment:
      - WEBDAV_DOMAIN
      - WEBDAV_USER_DATA
    image: ${DOCKER_IMAGE}
    expose:
      - 8080
    volumes:
      - ${WEBDAV_DIRECTORY}:/var/www/journal:rw
    networks:
      - web
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:${DOMAIN}"
      - "traefik.basic.port=8080"
      - "traefik.basic.protocol=http"

networks:
  web:
    external: true
